var num = parseInt(prompt("Enter a Number"));
var prime = num/2
if(num==1,num==0)
{
    console.log(num , "is Not a Prime Number");
    alert("Your Number is not prime");
    
}
else{
for (var a=2;a<=prime;a++)
{
    if(num % a == 0){
        console.log(num, "is not Prime Number");
        alert("Your Number is not prime");
    
    var f= 1;
    break;
}
}
if (f==0);{
    console.log(num, "is a Prime Number");
    alert("Your Number is Prime");
}
}
